### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by CRivasGomez** [CRivasGomez/wbs-notifier#1]
## Step 0: Prepare the repository

- [ ] Create the repository
- [ ] Create the project board for the launch roadmap
- [ ] Create the wiki of the project

## Step 1: Manage third-party services

- [ ] Create the Google Firebase project for using Firebase tools

## Step 2: Develop the domain model

- [ ] Design the domain model
- [ ] Document the domain model using UML
- [ ] Create JS classes representing the domain model

## Step 4: Interact with Firebase Realtime Database

- [ ] Implement a script for populating database with mock data
- [ ] Implement a script for reading data from database

## Step 5: Establish all possible notifications

- [ ] Brainstorm notifications than could be useful for a project depending on roles and schedules
- [ ] Document possible notifications included in this launch
